[master1]
device = /dev/ttyUSB0
baudrate = 9600
slave1 = /tmp/ttyCisco1
slave2 = /tmp/ttyCisco2
slave3 = /tmp/ttyCisco3
slave4 = /tmp/ttyCisco4

#[master2]
#device = /dev/ttyUSB1
#baudrate = 115200
#slave1 = /tmp/ttyHuawei_1
#slave2 = /tmp/ttyHuawei_2
#slave3 = /tmp/ttyHuawei_3
#slave4 = /tmp/ttyHuawei_4